site_name: Fiware-DataModels
site_url: https://fiware-datamodels.readthedocs.org
repo_url: https://github.com/fiware/dataModels.git
site_description: FIWARE Data Models Documentation
docs_dir: .
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  -  Home: index.md
  - 'Waste Management' : WasteManagement/doc/waste_management.md