site_name: Fiware-DataModels
site_url: https://fiware-datamodels.readthedocs.org
repo_url: https://github.com/fiware/dataModels.git
site_description: FIWARE Data Models Documentation
docs_dir: .
site_dir: html
markdown_extensions: [toc,fenced_code]
use_directory_urls: false
theme: readthedocs
extra_css: ["https://fiware.org/style/fiware_readthedocs.css"]
pages:
  -  Home: index.md
  -  PointOfInterest: 
      - 'WeatherStation'       : 'PointOfInterest/WeatherStation/doc/spec.md'
      - 'AirQualityStation'    : 'PointOfInterest/AirQualityStation/doc/spec.md'
  -  Parking:
      - 'StreetParking'        : 'Parking/StreetParking/doc/spec.md'
      - 'ParkingLot'           : 'Parking/ParkingLot/doc/spec.md'
  -  Ambient:
      - 'AmbientObserved'      : 'AmbientObserved/doc/spec.md'
      - 'AirQualityThreshold'  : 'AirQualityThreshold/doc/spec.md'
  -  Weather:
      - 'WeatherObserved'      : 'Weather/WeatherObserved/doc/spec.md'
      - 'WeatherForecast'      : 'Weather/WeatherForecast/doc/spec.md'
      - 'WeatherAlarm'         : 'Weather/WeatherAlarm/doc/spec.md'
  - 'Waste Management':
      - 'WasteContainerIsle'   : 'WasteManagement/WasteContainerIsle/doc/spec.md'
      - 'WasteContainerModel'  : 'WasteManagement/WasteContainerModel/doc/spec.md'
      - 'WasteContainer'       : 'WasteManagement/WasteContainer/doc/spec.md'